version: 2
jobs:
  'linux':
    docker:
      - image: circleci/node:8.12-stretch-browsers-legacy
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}'
      - run: 'sudo apt-get install python2.7 make gcc libxtst-dev libpng++-dev'
      - run: 'sudo npm i -g node-gyp'
      - run: 'npm i'
      - run: 'npm run rebuild'
      - save_cache:
          paths:
            - ./node_modules
          key: dependency-cache-{{ checksum "package.json" }}
      - run: 'npm run release-linux'